### ISSUE TITLE
Open Discussion

### ISSUE THREAD

**Issue by GeorgeS2019** [Malcolmnixon/GodotReadyPlayerMeAvatar#2]
@Malcolmnixon 

Although this is a test project, this is the FIRST the seriously integrate Ready Player Me to Godot advanced animations, linking Godot XR to vendor motion captures.

I think opening the discussion could direct the godot community here.

**Comment by GeorgeS2019** [comment]
@chrisl8

Here we will have people who are very up-to-date to the future of advanced 3D humanoid animation.

It would be great eventually we use Ready Player Me for [Godot4 IK demo project](https://github.com/godotengine/godot-demo-projects/pull/1036#issuecomment-2049756236)

FYI: I have no commercial conflict of interest with RPM.

**Comment by Malcolmnixon** [comment]
Hopefully this will be operational again in a few days once the breaking SkeletonModifier3D changes have been resolved. I'm most of the way through getting a PR which restores functionality.

**Comment by Malcolmnixon** [comment]
Godot latest has merged the XRTracker fix for the SkeletonModifier3D changes. I've updated this project to work with those changes.

**Comment by GeorgeS2019** [comment]
@Malcolmnixon 

I look through the codes commited.

Interesting re-designed of concepts 

Looking forward to learn what have and what have yet to be implemented before 4.3 beta that enable all your demos so far.

**Comment by GeorgeS2019** [comment]
Need the latest godot commit. 

> From Malcolm: The **XRBodyModifier3D** is now only responsible for "posing" the skeleton. Movement has to be done with an **XRNode3D** parent of the avatar which targets the same body_tracker and just moves itself (and all children) to the correct location.

![godot windows editor x86_64 mono_4GLM5AEUQU](https://github.com/Malcolmnixon/GodotReadyPlayerMeAvatar/assets/49812372/5a1937b0-297a-4ff9-abe7-da1b71ac31bc)

**Comment by GeorgeS2019** [comment]
Instead of Load_web,  I pre-downloaded the business avatar and saved as .glb. 
       
Then I use [Load_File](https://github.com/Malcolmnixon/GodotReadyPlayerMeAvatar/blob/0b1ae41577b658e07a96fc62ef0ad4a85442297e/addons/godot_rpm_avatar/rpm_loader.gd#L90) to load 

The avatar is slightly **distorted** (when the XRAnimator VMC protocol turned on).  Do u know reason?

How should the business avatar imported?  Is there something I need to care?


```python
#RpmLoader.load_web(%AvatarID.text, rpm_settings)
RpmLoader.load_file(%AvatarID.text, "res://BusinessMan/65fa409029044c117cbd3e3c.glb", rpm_settings)

```

**Comment by GeorgeS2019** [comment]
This is addressed. Go to ReadME, use the API to download correctly.
