### ISSUE TITLE
Do not understand these errors

### ISSUE THREAD

**Issue by GeorgeS2019** [Malcolmnixon/GodotReadyPlayerMeAvatar#5]
It is working. Just do not understand these errors

![image](https://github.com/Malcolmnixon/GodotReadyPlayerMeAvatar/assets/49812372/1a068084-229b-4a31-bab8-469caa777891)

**Comment by GeorgeS2019** [comment]
It seems not important

**Comment by Malcolmnixon** [comment]
These should be fixed with the latest Godot 3.4 master branch with https://github.com/godotengine/godot/pull/91031
